log_levels:
  default: debug
  management-refactor/internals/shared/activity: error
  management-refactor/internals/shared/db: debug
  management-refactor/internals/shared/permissions: debug
  management-refactor/internals/modules/peers/manager: warn
  management-integrations-refactor/integrations: info
